### ISSUE TITLE
Cannot set property '4' of undefined when game finished and component unmount

### ISSUE THREAD

**Issue by petrloukota** [brandly/react-tetris#7]
Hi,

there is an issue when game finished and component unmount. It ends up with error "Cannot set property '4' of undefined" on row

`
board[boardY][boardX] = className;
`

in function

`
createPieceSetter
`

Could you please fix this problem to let componnet unmount properly?

Thank you!

**Comment by brandly** [comment]
hi! thanks for taking a look at this repo. i just released `v0.1.1` which helps prevent the error you're seeing, but it's not perfect.

internally, these "stores" have their internal state strewn about as local variables:

https://github.com/brandly/react-tetris/blob/85f1e2c72a5aa16b90fd99f463b18a0b6af45d9c/src/js/stores/piece-store.js#L10-L15

which makes it hard to "reset" the game back to its starting state. as it currently stands, the game will end pretty smoothly but you can't yet get back to a new game. this is pretty restricting. 

maybe i'll get around to restructuring things here to provide more flexibility, but i've been pretty busy lately. 

what are you using `react-tetris` for? let me know if the new release works well.

**Comment by petrloukota** [comment]
Hi, thank you for the reply and new version release. Unfortunately, version 0.1.1 did not solve my problem. I'm using Tetris as an embed game in other application. An error is still the same while component unmounting.

**Comment by waleedarshad-vf** [comment]
Anybody found a solution for this

**Comment by waleedarshad** [comment]
@petrloukota how did you resolve it?

**Comment by brandly** [comment]
try `v0.1.2`! the issue should be gone. let me know if not!

**Comment by waleedarshad** [comment]
I am using same version but still facing the same problem.

**Comment by waleedarshad-vf** [comment]
let me try sorry

**Comment by waleedarshad-vf** [comment]
@brandly I have tried your solution. it is not causing exception but it is causing weird behavior when a player lost. Please look into the video 

https://www.loom.com/share/1cd9838d89c84d39872b79d764828ff8

**Comment by brandly** [comment]
Yeah the pieces keep piling up. Honestly this repo doesn’t have a good answer to this problem. 

There’s a lot of room to improve how this project is structured. On other issues, there’s been some discussion, like adding an event that fires when the game ends and adding a way to reset to a new game. None of these features have been implemented, but I’m open to hearing suggestions of what you would expect to happen when a game ends.

**Comment by waleedarshad-vf** [comment]
yes @brandly  resetting the application state seems a good option but if it is the time-consuming task,  at least it should be stopped like the one happening before adding the fix.

**Comment by brandly** [comment]
You’re probably right. I’ll reopen this and see if I can get to it. 

This is like the very first thing I made with React years ago. The core of it hasn’t changed since then, and the application state is really spread out. The real solution here requires a larger refactor to fix these structural issues.

**Comment by waleedarshad-vf** [comment]
@brandly sure. See at least if we can stop it. it will be a great help.
